name: withyou
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  google_sign_in: ^5.4.1
  google_maps_flutter: ^2.2.0
  http: ^0.13.5
  json_serializable: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.2.1


flutter:

  uses-material-design: true

  assets:
    - assets/locations.json
